skip_local_validator = false

[toolchain]

[workspace]
members = [
    "programs/*",
]
idls = "client/src/idl"
types = "client/src/idl"

[features]
resolution = true
skip-lint = false

[programs.localnet]
guardrail = "HP8ptgh4CDEwgR7rSESkfR4ZxyrLcg5VfkossDLwU5RS"

[programs.devnet]
guardrail = "HP8ptgh4CDEwgR7rSESkfR4ZxyrLcg5VfkossDLwU5RS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
